In [1]:
import numpy as np
import pandas as pd
import os, sys
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
df=pd.read_csv('parkinsons.data')
df.head()

name  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  ...   spread2        D2       PPE
0  phon_R01_S01_1      119.992       157.302  ...  0.266482  2.301442  0.284654
1  phon_R01_S01_2      122.400       148.650  ...  0.335590  2.486855  0.368674
2  phon_R01_S01_3      116.682       131.111  ...  0.311173  2.342259  0.332634
3  phon_R01_S01_4      116.676       137.871  ...  0.334147  2.405554  0.368975
4  phon_R01_S01_5      116.014       141.781  ...  0.234513  2.332180  0.410335

[5 rows x 24 columns]

In [3]:
df.describe()

MDVP:Fo(Hz)  MDVP:Fhi(Hz)  ...          D2         PPE
count   195.000000    195.000000  ...  195.000000  195.000000
mean    154.228641    197.104918  ...    2.381826    0.206552
std      41.390065     91.491548  ...    0.382799    0.090119
min      88.333000    102.145000  ...    1.423287    0.044539
25%     117.572000    134.862500  ...    2.099125    0.137451
50%     148.790000    175.829000  ...    2.361532    0.194052
75%     182.769000    224.205500  ...    2.636456    0.252980
max     260.105000    592.030000  ...    3.671155    0.527367

[8 rows x 23 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   name              195 non-null    object 
 1   MDVP:Fo(Hz)       195 non-null    float64
 2   MDVP:Fhi(Hz)      195 non-null    float64
 3   MDVP:Flo(Hz)      195 non-null    float64
 4   MDVP:Jitter(%)    195 non-null    float64
 5   MDVP:Jitter(Abs)  195 non-null    float64
 6   MDVP:RAP          195 non-null    float64
 7   MDVP:PPQ          195 non-null    float64
 8   Jitter:DDP        195 non-null    float64
 9   MDVP:Shimmer      195 non-null    float64
 10  MDVP:Shimmer(dB)  195 non-null    float64
 11  Shimmer:APQ3      195 non-null    float64
 12  Shimmer:APQ5      195 non-null    float64
 13  MDVP:APQ          195 non-null    float64
 14  Shimmer:DDA       195 non-null    float64
 15  NHR               195 non-null    float64
 16  HNR               195 non-null    float64
 1

In [5]:
df.corr()

MDVP:Fo(Hz)  MDVP:Fhi(Hz)  ...        D2       PPE
MDVP:Fo(Hz)          1.000000      0.400985  ...  0.177980 -0.372356
MDVP:Fhi(Hz)         0.400985      1.000000  ...  0.176323 -0.069543
MDVP:Flo(Hz)         0.596546      0.084951  ... -0.100629 -0.340071
MDVP:Jitter(%)      -0.118003      0.102086  ...  0.433434  0.721543
MDVP:Jitter(Abs)    -0.382027     -0.029198  ...  0.310694  0.748162
MDVP:RAP            -0.076194      0.097177  ...  0.426605  0.670999
MDVP:PPQ            -0.112165      0.091126  ...  0.412524  0.769647
Jitter:DDP          -0.076213      0.097150  ...  0.426556  0.671005
MDVP:Shimmer        -0.098374      0.002281  ...  0.507088  0.693771
MDVP:Shimmer(dB)    -0.073742      0.043465  ...  0.512233  0.695058
Shimmer:APQ3        -0.094717     -0.003743  ...  0.467265  0.645377
Shimmer:APQ5        -0.070682     -0.009997  ...  0.502174  0.702456
MDVP:APQ            -0.077774      0.004937  ...  0.536869  0.721694
Shimmer:DDA         -0.094732     -0.003733  ...  0.467261  0.645389
NHR                 -0.021981      0.163766  ...  0.470949  0.552591
HNR                  0.059144     -0.024893  ... -0.601401 -0.692876
status              -0.383535     -0.166136  ...  0.340232  0.531039
RPDE                -0.383894     -0.112404  ...  0.236931  0.545886
DFA                 -0.446013     -0.343097  ... -0.165381  0.270445
spread1             -0.413738     -0.076658  ...  0.495123  0.962435
spread2             -0.249450     -0.002954  ...  0.523532  0.644711
D2                   0.177980      0.176323  ...  1.000000  0.480585
PPE                 -0.372356     -0.069543  ...  0.480585  1.000000

[23 rows x 23 columns]

In [6]:
features=df.loc[:,df.columns!='status'].values[:,1:]
features

array([[119.992, 157.302, 74.997, ..., 0.266482, 2.3014419999999998,
        0.284654],
       [122.4, 148.65, 113.819, ..., 0.33559, 2.486855, 0.368674],
       [116.682, 131.111, 111.555, ..., 0.311173, 2.342259,
        0.33263400000000004],
       ...,
       [174.688, 240.005, 74.287, ..., 0.158453, 2.6797720000000003,
        0.13172799999999998],
       [198.764, 396.961, 74.904, ..., 0.207454, 2.138608, 0.123306],
       [214.289, 260.277, 77.973, ..., 0.190667, 2.555477, 0.148569]],
      dtype=object)

In [7]:
status=df.loc[:,'status'].values
status

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
df['status'].value_counts()

1    147
0     48
Name: status, dtype: int64

In [9]:
X=features
y=status

In [10]:
X_train,X_test,y_train,y_test=train_test_split(X, y, test_size=0.25, random_state=101)

In [11]:
X_train
y_train

array([1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1])

In [12]:
scaler=StandardScaler()
scaled_X_train=scaler.fit_transform(X_train)
scaled_X_test=scaler.fit_transform(X_test)
scaled_X_train
scaled_X_test

array([[ 0.54855928, -0.09413716,  0.84178276, ...,  0.6521994 ,
         0.07009021, -0.42253481],
       [-1.13459911, -0.82636856, -0.61659709, ..., -0.41542195,
        -1.28836678,  0.18929747],
       [ 1.34204855,  0.28581896, -0.59463098, ..., -1.6982446 ,
        -0.09213521, -1.15794076],
       ...,
       [ 1.74375918,  0.38786811,  1.99066647, ..., -0.76215541,
        -0.26467395, -0.93491402],
       [ 0.88034522,  3.67211585,  0.92375481, ...,  0.5921623 ,
         1.47375879,  0.87323117],
       [-0.76070248,  2.78041128, -0.79580347, ...,  0.82199853,
         0.87796131, -0.52033092]])

In [13]:
scaled_X_test.mean(axis=0)

array([ 3.98773984e-16,  6.61602292e-16,  3.08143533e-16, -6.58132845e-17,
       -5.98160977e-16,  3.44395714e-16, -3.67619767e-16,  1.40477199e-16,
        1.47274483e-16, -1.35945676e-16, -4.53152255e-18,  2.12981560e-16,
        4.29361762e-16, -2.94548966e-17,  5.72104722e-17,  2.16380202e-15,
       -9.83659016e-16,  4.07837029e-16,  1.08076813e-15,  8.11142536e-16,
        1.06717356e-15,  0.00000000e+00])

In [14]:
from sklearn.linear_model import LogisticRegressionCV
log_model=LogisticRegressionCV(max_iter=10000)
log_model.fit(scaled_X_train,y_train)

LogisticRegressionCV(Cs=10, class_weight=None, cv=None, dual=False,
                     fit_intercept=True, intercept_scaling=1.0, l1_ratios=None,
                     max_iter=10000, multi_class='auto', n_jobs=None,
                     penalty='l2', random_state=None, refit=True, scoring=None,
                     solver='lbfgs', tol=0.0001, verbose=0)

In [15]:
y_pred=log_model.predict(scaled_X_test)

In [16]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[10  3]
 [ 0 36]]
              precision    recall  f1-score   support

           0       1.00      0.77      0.87        13
           1       0.92      1.00      0.96        36

    accuracy                           0.94        49
   macro avg       0.96      0.88      0.91        49
weighted avg       0.94      0.94      0.94        49



In [17]:
from sklearn.neighbors import KNeighborsClassifier
knn_model=KNeighborsClassifier(n_neighbors=1)
knn_model.fit(scaled_X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [18]:
y_pred=knn_model.predict(scaled_X_test)

In [19]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[12  1]
 [ 4 32]]
              precision    recall  f1-score   support

           0       0.75      0.92      0.83        13
           1       0.97      0.89      0.93        36

    accuracy                           0.90        49
   macro avg       0.86      0.91      0.88        49
weighted avg       0.91      0.90      0.90        49



In [20]:
from xgboost import XGBClassifier
xgb_model=XGBClassifier()
xgb_model.fit(scaled_X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [22]:
y_pred=xgb_model.predict(scaled_X_test)

In [23]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 7  6]
 [ 0 36]]
              precision    recall  f1-score   support

           0       1.00      0.54      0.70        13
           1       0.86      1.00      0.92        36

    accuracy                           0.88        49
   macro avg       0.93      0.77      0.81        49
weighted avg       0.90      0.88      0.86        49

